- name: Ensure Python3-pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure required Python libraries are installed
  pip:
    name:
      - docker
      - requests
      - packaging
    executable: pip3

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker daemon is running
  shell: |
    pgrep dockerd || dockerd &
  async: 10
  poll: 0