services:
  ansible-control:
    build: ./control
    container_name: ansible-control
    volumes:
      - .:/ansible

  dev:
    build: ./node
    container_name: dev

  prod:
    build: ./node
    container_name: prod

  jenkins:
    build: ./jenkins
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: